name: Sanity checks

on:
    pull_request:
        branches:
            - main

jobs:
    sanity:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7
            - name: setup Node.js
              uses: actions/setup-node@v4.0.3
            - name: Install dependencies
              run: yarn
            - name: Run Prettier
              run: yarn run format
            - name: Run Eslint
              run: yarn run lint
